# Generated by Django 4.2 on 2025-01-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessUser',
        ),
    ]
