# Generated by Django 4.2 on 2025-01-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_add_learning_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='assignedUsername',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
