version: '3'

services:
  backend:
    build: ./backend
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - /etc/timezone:/etc/timezone:ro  # Opcjonalnie, jeśli chcesz użyć lokalnej strefy czasowej
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8000:8000"
    depends_on:
     - postgres
    environment:
      - TZ=Europe/Warsaw


  ui-app:
    build: ./ui-app
    ports:
      - "8080:80" 
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000/api
      - TZ=Europe/Warsaw


  postgres:
    image: postgres:13
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      TZ: Europe/Warsaw
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
